### ISSUE TITLE
Cannot install new app

### ISSUE THREAD

**Issue by hchoriq** [infinitered/ignite-ir-boilerplate-2016#11]
I followed the instructions and upon ignite new MonitoringApp, I get this:

🔥 igniting app MonitoringApp
✔ using the Infinite Red boilerplate
✔ added React Native 0.42.0
an error occured while installing ignite-ir-boilerplate-2016 boilerplate.
Error: ENOENT: no such file or directory, uv_chdir

**Comment by stickiz** [comment]
^ this

**Comment by skellock** [comment]
Do you have `react-native` installed globally?  if so, `npm rm -g react-native` and try again.

**Comment by hchoriq** [comment]
Nope, no-go. Now using node v7.7.2 (npm v4.1.2)

**Comment by skellock** [comment]
Can you try this with forcing npm instead of yarn? Add --npm to your command.

**Comment by nonameolsson** [comment]
I get the same error, even with `--npm` @skellock

**Comment by GantMan** [comment]
are any of you available to do a screen share soon so we can identify what's happening?

ALSO:
what's the output of `ignite doctor`?

**Comment by derekgreenberg** [comment]
@stickiz  @hchoriq  @nonameolsson - If you have a node_modules subdirectory in the directory that you are in when issuing the `ignite new ...` command, remove it and try again. Was this the issue and if so, did it fix the issue for you?

**Comment by skellock** [comment]
We're [tracking this over here](https://github.com/infinitered/ignite/issues/913).  If this is indeed the problem you're having 🤞 then we can close up this issue.

**Comment by nonameolsson** [comment]
@GantMan
Here's a video when the error occurs: https://youtu.be/6it6dxjAEMQ

@derekgreenberg I create a new folder and try to run `ignite new` from that one. There is no `node_modules` in that folder.

@skellock When I do the thing you have described in that post I also get an error.

`ignite doctor`
```
ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores                                                  Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  directory          /Users/nonameolsson/Development/ReactNative/ignitetest

JavaScript
  node               7.6.0        /Users/nonameolsson/.nvm/versions/node/v7.6.0/bin/node
  npm                4.1.2        /Users/nonameolsson/.nvm/versions/node/v7.6.0/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

React Native
  react-native-cli   0.1.10

Ignite
  ignite             2.0.0-beta.6   /Users/nonameolsson/.nvm/versions/node/v7.6.0/bin/ignite

Android
  java               1.8.0_112    /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              8.2.1
```

**Comment by skellock** [comment]
I see you are using nvm. Where do you set which version of node? Is it in your .bash_profile by any chance?

**Comment by nonameolsson** [comment]
@skellock No, I haven't added anything to my `.bash_profile`. I set the version of npm through nvm.

**Comment by skellock** [comment]
How does that happen?  I'm not that familiar with `nvm`.  Do you have a line of code in a `.zshrc` file that sets `nvm use 7.6` or something?

**Comment by skellock** [comment]
Ahhh... 

Upgrade `npm i -g react-native-cli` to the latest version.  `0.1.10` is causing this problem.  It's fixed in `2.0.1`.

I'll spin up a new issue to make this a requirement.

If you can confirm, we'll close this issue.

**Comment by nonameolsson** [comment]
That seems to be the case! I did follow the instructions here:  [https://facebook.github.io/react-native/docs/upgrading.html#upgrade-based-on-git](https://facebook.github.io/react-native/docs/upgrading.html#upgrade-based-on-git)

Now it works! Great, thank you very much for your help!

**Comment by moses5407** [comment]
I don't know if commenting reopens this.. HOpefully so.

I'm getting a different error and this has continued after trying the react-native cli update mentioned.

I get "an error occured while installing ignite-r-boilerplate-2016 boilerplate"
Error: Command failed git-commit-m "Initial commit"
Please tell me who you are"

It then sticks on configuring git

**Comment by khaledalyawad** [comment]
I had the similar issue, nothing above worked for me, 
My solution was:
I went to my {name}/node-module and deleted all my installed node modules.

**Comment by GantMan** [comment]
Fixing node issues is like half of what we do, heh.

Def nuke node-modules as an option when stuck.  I don't know why node has to be so angry at times.

**Comment by moses5407** [comment]
deleting node modules in the project directory is ok?

**Comment by moses5407** [comment]
my mistake ...this means deleting node-modules in the Ignite directory? I'm confused about the "where" and the potential effect on anything else relying on node_modules

**Comment by Chandrasekar-G** [comment]
I still get the same error. Deleting the node_modules and upgrading the cli didn't solve the issue in my case,

` ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores                                                  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  directory          /Users/chandrasekarg/Projects/POCs/React Native/ignite

JavaScript
  node               7.8.0        /Users/chandrasekarg/.nvm/versions/node/v7.8.0/bin/node
  npm                4.2.0        /Users/chandrasekarg/.nvm/versions/node/v7.8.0/bin/npm
  yarn               0.27.5       /Users/chandrasekarg/.nvm/versions/node/v7.8.0/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /Users/chandrasekarg/.nvm/versions/node/v7.8.0/bin/ignite

Android
  java               1.8.0_121    /usr/bin/java
  android home       -            /Applications/android-sdk-macosx

iOS
  xcode              8.2.1`

**Comment by pribeh** [comment]
I kept getting the cannot 'boilerplate is not available on npm' message. After deleting the base node_modules everything worked fine.

**Comment by andytwoods** [comment]
I updated node. Works now.

**Comment by uditj06** [comment]
I am facing the same issue but not able to resolve it. 
Output of Ignite Doctor is:
System
  platform           win32
  arch               x64
  cpu                4 cores      Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  directory          E:\test

JavaScript
  node               10.8.0       C:\Program Files\nodejs\node.EXE
  npm                6.2.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.9.4        C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.1        C:\Users\dell\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\dell\AppData\Local\Android\Sdk

When I enter the command ignite new MyApp it gices the following error:
× ignite-ir-boilerplate was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate --dev
error Couldn't find the binary git

----------
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
an error occured while installing ignite-ir-boilerplate boilerplate.
Error: not found: git

Can anyone please prove me step by step resolution of the problem as I am very much new to the platform?

**Comment by jamonholmgren** [comment]
@uditj06  It looks like you need to install git. You can do so here: https://git-scm.com/downloads.

**Comment by ibanezzaro** [comment]
> deleting node_module from home directory solved this issue for me.

This worked for me too, having the same problem as OP.

**Comment by irony** [comment]
Installing ignite with npm produces this error for me. By installing the ignite-cli with yarn instead it worked.
