### ISSUE TITLE
Error on Dev Screens - Device Info - Android

### ISSUE THREAD

**Issue by Nevtep** [infinitered/ignite-ir-boilerplate-2016#14]
I just created a new app to try Ignite with 

    Ignite new TestApp

Answered yes to all the options, ios emulator looks fine, but on android when going to Device Info Screen I got a big red screen with this error:

To use NetInfo on Android, add the following to your AndroidManifest.xml:
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<unknown>
    NativeModules.js:79:57
__invokeCallback
    MessageQueue.js:288:19
<unknown>
    MessageQueue.js:127:28
guard
    MessageQueue.js:46:4
invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:126:10

Maybe the Dev Screens should add that parameter to the manifest, but it seems sane to keep it out by default.

**Comment by GantMan** [comment]
I'm on it.

**Comment by GantMan** [comment]
been a busy morning, but I have the code in place, I just need to test it:
https://github.com/infinitered/ignite/tree/add_android_permission

**Comment by GantMan** [comment]
I also think we need to backfill tests for all our ignite helpers.   I know it's been busy, but it's time.
