### ISSUE TITLE
Update Branding Graphics

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-2016#21]
@cindy-nguyen has give us some updated branding graphics.  Let's put these in place.

[Updates 03222017.zip](https://github.com/infinitered/ignite-ir-boilerplate-2016/files/865638/Updates.03222017.zip)

**Comment by GantMan** [comment]
shouldn't we do this on next?

**Comment by jamonholmgren** [comment]
@GantMan I think if it doesn't break compatibility we should do it on both.

**Comment by GantMan** [comment]
sounds good.  I mean priority is to do it in next.

**Comment by GantMan** [comment]
I want to start making it flow the way it will continue to flow from here forward.   We will stamp versions of Next to be moments in tech.

**Comment by jamonholmgren** [comment]
We'll do this in `next`.
