### ISSUE TITLE
Branches vs Repos

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-2016#24]
How would you feel if used branches instead of repos to do our `ignite-ir-boilerplate-*` forking?

We'd get to keep history and have one place to manage.  I believe having multiple repos might be a bit unwieldy.

/cc @jamonholmgren @GantMan @kevinvangelder @derekgreenberg @robinheinze

**Comment by jamonholmgren** [comment]
We decided in our last Ignite meeting to do branches rather than repos. 👍
