### ISSUE TITLE
failing new project creation

### ISSUE THREAD

**Issue by moses5407** [infinitered/ignite-ir-boilerplate-2016#27]
I don't know if commenting reopens this.. HOpefully so.

I'm getting a different error and this has continued after trying the react-native cli update mentioned.

I get "an error occured while installing ignite-r-boilerplate-2016 boilerplate"
Error: Command failed git-commit-m "Initial commit"
Please tell me who you are"

It then sticks on configuring git

**Comment by moses5407** [comment]
I should add I DID try the git-config suggested in the extended error message but got invalid key or key does not contain a section:global

**Comment by jamonholmgren** [comment]
Hey @moses5407 , did you get this figured out yet?

**Comment by jamonholmgren** [comment]
Closing as abandoned ... feel free to comment if this is still an issue.
