### ISSUE TITLE
Semaphore tests failing

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite-ir-boilerplate-2016#31]
Despite passing locally, semaphore builds are failing. We need to get these fixed.

**Comment by skellock** [comment]
Got them passing.  It was `yarn`.  We were installing it via `npm` which isn't cool on Linux for reasons.  Semaphore ships with `0.21.3` which is good enough, so we no longer install it in the Semaphore setup.

**Comment by jamonholmgren** [comment]
ty sir!
