### ISSUE TITLE
Ava component tests using Enzyme have warnings

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite-ir-boilerplate-2016#34]
These warnings appear when running `npm test`

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.

**Comment by jamonholmgren** [comment]
@derekgreenberg Any plans to fix this? You might hold off ... this boilerplate is unlikely to stay the default much longer.

**Comment by derekgreenberg** [comment]
Fixed with https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/35

**Comment by jamonholmgren** [comment]
Thank you!
