### ISSUE TITLE
Problem with "ignite generate screen PizzaLocationList"

### ISSUE THREAD

**Issue by tokgozmusa** [infinitered/ignite-ir-boilerplate-2016#37]
Hey,

@jamonholmgren kindly asked me to mention this bug here. You can see the first issue related with this link: https://github.com/infinitered/ignite/issues/1015

I think there is an inconsistency when we generate screens by the command that ignite provides.
```
$ ignite generate screen PizzaLocationList
```

After run this command we will have 2 autogenerated files: 
✔︎ App/Containers/PizzaLocationListScreen.js
✔︎ App/Containers/Styles/PizzaLocationListScreenStyle.js

Inside `PizzaLocationListScreen.js` file we see the following autogenerated line.
```
import styles from './Styles/PizzaLocationListStyle'
```

As we can see there is an inconsistency with file names. That autogenerated file should have been as follows:
```
import styles from './Styles/PizzaLocationListScreenStyle'
```

Notes:
- I use ignite version `2.0.0-beta.9`.
- I installed ignite by `npm install -g ignite-cli` command.
- I created my first app by `ignite new PizzaApp` command.
- Apparently ignite-cli uses `ignite-ir-boilerplate-2016` boilerplate.

Thank you for your considerations.

**Comment by jamonholmgren** [comment]
Thanks @tokgozmusa !
