### ISSUE TITLE
Cann't Run react native Project on IOS simulator.

### ISSUE THREAD

**Issue by NiteshGarg2107** [infinitered/ignite-ir-boilerplate-2016#44]
When I tried to run the react native project It show me this error.
ENOENT: no such file or directory, uv_chdir
[Error] "Could not debug. Error while executing command 'react-native run-ios --simulator iPhone 6s --project-path ios': Error while executing command 'react-native run-ios --simulator iPhone 6s --project-path ios'"

**Comment by jamonholmgren** [comment]
Hey @NiteshGarg2107 , sorry about the slow reply. Do any of the suggestions in [this thread](https://github.com/infinitered/ignite-ir-boilerplate-2016/issues/11) work for you?
