### ISSUE TITLE
Add some demo screens

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-2016#6]
Someone in our slack channel was asking about seeing some screens in action like we had in Ignite 1.0.  

That'd be great to have for instructional purposes.  Not sure if it needs to be in here? Or maybe a separate demo repo?

**Comment by GantMan** [comment]
we can kitchen sink it still for people to use as examples, but keep it out of their project.

I think some open source apps written in Ignite would be the most attractive.  Especially if they are released to the store.

**Comment by skellock** [comment]
Ya, I know you've mentioned that before (about OSS + store).  That'd be tremendous!  We're all overworked right now, so no rush.

**Comment by jamonholmgren** [comment]
Going to push this toward `ir-next` if we still want to do it.
