### ISSUE TITLE
Fails to run on Android

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-2016#7]
Out of the box, this fails to run on Android.

It builds, but just crashes.  I haven't tested this myself yet, but have heard from a few people.

I'll `adb logcat` for more answers once I have some time.

**Comment by mwarger** [comment]
What do you mean by out of the box?  Can you specify the setup (I assume using ignite-cli?)  I can help test on the android side.

**Comment by skellock** [comment]
I cant reproduce this either.  🎉
